# -*- coding: utf-8 -*-
"""HW1 三種演算法比較.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dthuHGzUu9lYBPQZmUgJu-B0HGRKVI2v
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython
# %R install.packages("C50")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from chefboost import Chefboost as chef

#%%
##前處理
# 檔案路徑
train_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
test_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"

# 欄位名稱
cols = [
    "age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
    "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
    "hours-per-week", "native-country", "income"
]

# 讀取資料
df_train = pd.read_csv(train_url, names=cols, sep=",", skipinitialspace=True)
df_test = pd.read_csv(test_url, names=cols, sep=",", skipinitialspace=True, skiprows=1)

# 合併資料
df = pd.concat([df_train, df_test], ignore_index=True)

# 處理缺失值'?'
df = df.replace('?', pd.NA).dropna()
df['income'] = df['income'].apply(lambda s: s.strip().strip('.'))

# 取得文字欄位
cat_cols = df.select_dtypes(include=['object']).columns
num_cols = df.select_dtypes(exclude=['object']).columns
for c in cat_cols:
    df[c] = df[c].astype(str)

cat_cols = cat_cols.drop('income')

# 資料分割
train_df, test_df = train_test_split(df, test_size=0.3, random_state=42)

results = []
pred_table = pd.DataFrame()
pred_table['True'] = test_df['income'].tolist()

# 特徵與標籤
X_train = train_df.drop('income', axis=1)
y_train = train_df['income']
X_test  = test_df.drop('income', axis=1)
y_test  = test_df['income']


# OneHot 編碼器
encoder = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
    ('num', 'passthrough', num_cols)
])

# 編碼後
X_train_enc = encoder.fit_transform(X_train)
X_test_enc  = encoder.transform(X_test)

id3 = DecisionTreeClassifier(criterion='entropy', random_state=42)
id3.fit(X_train_enc, y_train)

#%%
# 預測
y_true = y_test.tolist()
y_pred = id3.predict(X_test_enc)

# 計算準確率
acc = accuracy_score(y_true, y_pred)
print(f"ID3 準確率：{acc:.4f}")
results.append(('ID3', acc))

#%%
# 存入excel
pred_table['ID3'] = y_pred
#%%
config = {'algorithm': 'C4.5'}
model = chef.fit(train_df, config, target_label='income')

#%%
# 預測
y_true = test_df['income'].tolist()
y_pred = [chef.predict(model, row.tolist()) for _, row in test_df.iterrows()]

# 計算準確率
acc = accuracy_score(y_true, y_pred)
results.append(("C4.5", acc))
print(f"C4.5 準確率：{acc:.4f}")

#%%
# 存入excel
pred_table["C4.5"] = y_pred

clf = DecisionTreeClassifier(criterion='gini', random_state=42)
clf.fit(X_train_enc, y_train)

#%%
# 預測
y_true = y_test.tolist()
y_pred = clf.predict(X_test_enc)

# 計算準確率
acc = accuracy_score(y_true, y_pred)
print(f"Cart 準確率：{acc:.4f}")
results.append(('Cart', acc))

#%%
# 存入excel
pred_table['Cart'] = y_pred

import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr

#%%
# 啟用 pandas 與 R dataframe 轉換
pandas2ri.activate()

# 匯入 R 的 C50 套件
C50 = importr('C50')

# 轉換為 R 的 factor
train_df['income'] = train_df['income'].astype('category')
test_df['income']  = test_df['income'].astype('category')

# 將資料轉成 R dataframe
ro.globalenv['train_data'] = pandas2ri.py2rpy(train_df)
ro.globalenv['test_data'] = pandas2ri.py2rpy(test_df)

# 安裝與載入 C50 套件
ro.r('library(C50)')

# 訓練 + 預測
ro.r('model <- C5.0(income ~ ., data=train_data)')
ro.r('pred <- predict(model, test_data)')

# 轉回 Python
y_true_c50 = list(test_df['income'])
y_pred_c50 = list(ro.r('as.character(pred)'))

# 準確率
acc_c50 = accuracy_score(y_true_c50, y_pred_c50)
results.append(('C5.0', acc_c50))
print(f"C5.0 準確率：{acc_c50:.4f}")

#%%
# 存入excel
pred_table['C5.0'] = y_pred_c50

#%%
# 匯總與輸出
acc_df = pd.DataFrame(results, columns=["Algorithm", "Accuracy"])

with pd.ExcelWriter('decision_tree_all_results.xlsx') as writer:
    pred_table.to_excel(writer, sheet_name='Predictions', index=False)
    acc_df.to_excel(writer, sheet_name='Accuracy Summary', index=False)

print(acc_df)